### ISSUE TITLE
About the Client

### ISSUE THREAD

**Issue by xinghanjiang** [jiayiwang5/socket_java#1]
Hello,
Am new for java and have a problem when I run the Client, there was shown the "加载MySQL驱动失败!". 
Can I know what is this problem mean?
Or have ur help to fix it?

**Comment by jayeew** [comment]
> Hello,
> Am new for java and have a problem when I run the Client, there was shown the "加载MySQL驱动失败!".
> Can I know what is this problem mean?
> Or have ur help to fix it?

maybe the version of Java does not match the version of mysql jar
